

self.Direction = self.faces[0][0].Shape.getElement(self.faces[0][1]).normalAt(0,0)

FreeCADGui.Selection.getSelectionEx("",1)[0].Shape.getElement(FreeCADGui.Selection.getSelectionEx("",0)[0].SubElementNames[0])
FreeCADGui.Selection.getSelectionEx("",1)[0].Object.Shape.getElement(FreeCADGui.Selection.getSelectionEx()[0].SubElementNames[0]).normalAt(0,0)

FreeCADGui.Selection.getSelectionEx("",1)[0].Object.Shape.getElement(FreeCADGui.Selection.getSelectionEx("",1)[0].SubElementNames[0]).normalAt(0,0)

FreeCADGui.Selection.getSelectionEx("",1)[0].Object.Shape.getElement(FreeCADGui.Selection.getSelectionEx("",1)[0].SubElementNames[0]).CenterOfMass

